### ISSUE TITLE
got 120 ohms constraint gauge, you specified 350ohms, is that a problem ? 

### ISSUE THREAD

**Issue by cfournel** [rrrlasse/powerino#3]
not really an issue here, but circuit may need adjustement to get correct results with 120 ohm constraint gauge .

any idea ? 

thanks a lot !

**Comment by rrrlasse** [comment]
I think 120 ohm strain gauges should work with no changes or adjustments of anything. The calibration step in the Android app just sees a voltage change for a known given load and doesn't care about the absolute resistance.

**Comment by cfournel** [comment]
thanks ! 

great news !
